import type { Candidate, Application, Interview, Job } from "@/types/domain.types";
import type { TimelineItem } from "@/components";

export const mockCandidate: Candidate = {
  id: "cand_123",
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
  userId: "user_123",
  firstName: "Alex",
  lastName: "Chen",
  fullName: "Alex Chen",
  email: "alex.chen@example.com",
  phone: "+1 (555) 123-4567",
  avatarUrl: "https://i.pravatar.cc/150?u=alex",
  headline: "Senior Frontend Engineer | React & Next.js Expert",
  summary: "Passionate about building accessible, performant, and delightful web experiences. 6+ years of experience in modern JavaScript ecosystems.",
  status: "ACTIVE",
  skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js", "GraphQL"],
  experience: [
    {
      id: "exp_1",
      company: "TechNova",
      title: "Senior Frontend Engineer",
      startDate: "2021-03-01",
      isCurrent: true,
      description: "Led the frontend architecture migration to Next.js App Router.",
    },
    {
      id: "exp_2",
      company: "WebSolutions Inc",
      title: "Frontend Developer",
      startDate: "2018-06-01",
      endDate: "2021-02-28",
      isCurrent: false,
    },
  ],
  education: [
    {
      id: "edu_1",
      institution: "University of Technology",
      degree: "Bachelor of Science",
      field: "Computer Science",
      startDate: "2014-09-01",
      endDate: "2018-05-30",
    }
  ],
  resumeUrl: "https://example.com/resume.pdf",
  linkedinUrl: "https://linkedin.com/in/alexc",
  portfolioUrl: "https://alexchen.dev",
  location: "San Francisco, CA",
  isOpenToRelocation: false,
  expectedSalary: 140000,
  expectedSalaryCurrency: "USD",
};

export const mockApplications: Application[] = [
  {
    id: "app_1",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    candidateId: mockCandidate.id,
    jobId: "job_1",
    job: {
      id: "job_1",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: "Staff Product Engineer",
      description: "...",
      requirements: [],
      responsibilities: [],
      status: "PUBLISHED",
      type: "FULL_TIME",
      experienceLevel: "LEAD",
      location: "San Francisco, CA",
      isRemote: true,
      skills: ["React", "TypeScript", "System Design"],
      tags: [],
      companyId: "comp_1",
      postedById: "user_rec_1",
      applicationCount: 42,
      viewCount: 150,
    },
    status: "INTERVIEW",
    currentStage: "Technical Assessment",
  },
  {
    id: "app_2",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    candidateId: mockCandidate.id,
    jobId: "job_2",
    job: {
      id: "job_2",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: "Frontend Architect",
      description: "...",
      requirements: [],
      responsibilities: [],
      status: "PUBLISHED",
      type: "FULL_TIME",
      experienceLevel: "LEAD",
      location: "New York, NY",
      isRemote: true,
      skills: ["Next.js", "Architecture", "Performance"],
      tags: [],
      companyId: "comp_2",
      postedById: "user_rec_2",
      applicationCount: 12,
      viewCount: 89,
    },
    status: "SCREENING",
    currentStage: "Recruiter Screen",
  },
  {
    id: "app_3",
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    candidateId: mockCandidate.id,
    jobId: "job_3",
    job: {
      id: "job_3",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: "Senior UI Engineer",
      description: "...",
      requirements: [],
      responsibilities: [],
      status: "CLOSED",
      type: "FULL_TIME",
      experienceLevel: "SENIOR",
      location: "Austin, TX",
      isRemote: false,
      skills: ["React", "CSS"],
      tags: [],
      companyId: "comp_3",
      postedById: "user_rec_3",
      applicationCount: 200,
      viewCount: 500,
    },
    status: "REJECTED",
    currentStage: "Final Round",
  }
];

export const mockInterviews: Interview[] = [
  {
    id: "int_1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    applicationId: "app_1",
    title: "System Design & Architecture",
    type: "TECHNICAL",
    status: "SCHEDULED",
    scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // in 2 days
    durationMinutes: 60,
    meetingLink: "https://meet.google.com/abc-defg-hij",
    participants: [
      {
        userId: "p_1",
        name: "Sarah Jenkins",
        email: "sarah@technova.com",
        role: "Engineering Manager",
        isLead: true,
        avatarUrl: "https://i.pravatar.cc/150?u=sarah",
      }
    ]
  }
];

export const mockRecommendedJobs: Job[] = [
  {
    id: "rec_job_1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: "Lead Frontend Engineer",
    description: "Join our core platform team to lead the frontend transition.",
    requirements: [],
    responsibilities: [],
    status: "PUBLISHED",
    type: "FULL_TIME",
    experienceLevel: "LEAD",
    location: "Remote (US)",
    isRemote: true,
    salaryRange: { min: 160000, max: 200000, currency: "USD" },
    skills: ["React", "TypeScript", "GraphQL", "Performance"],
    tags: ["High Growth", "Fintech"],
    companyId: "comp_10",
    postedById: "user_10",
    applicationCount: 15,
    viewCount: 200,
  },
  {
    id: "rec_job_2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    title: "Senior UX Engineer",
    description: "Bridge the gap between design and engineering.",
    requirements: [],
    responsibilities: [],
    status: "PUBLISHED",
    type: "FULL_TIME",
    experienceLevel: "SENIOR",
    location: "New York, NY",
    isRemote: false,
    salaryRange: { min: 145000, max: 175000, currency: "USD" },
    skills: ["React", "Tailwind CSS", "Figma", "Framer Motion"],
    tags: ["Design Systems", "Series B"],
    companyId: "comp_11",
    postedById: "user_11",
    applicationCount: 32,
    viewCount: 410,
  }
];

export const mockTimelineEvents: TimelineItem[] = [
  {
    id: "t_1",
    status: "info",
    title: "Application Submitted",
    description: "You applied for Staff Product Engineer at TechNova",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t_2",
    status: "success",
    title: "Interview Scheduled",
    description: "Technical assessment scheduled for this Thursday",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t_3",
    status: "warning",
    title: "Profile Incomplete",
    description: "Please add your recent projects to boost your match rate.",
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
